In [31]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [32]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [33]:
metadata = pd.read_csv("/content/drive/MyDrive/skripsi_nau/metadata/naudataset.csv")

metadata.head()

   id  nama_gambar            aktivitas warna_dominan hijab undertone
0   1  img0001.jpg  coffee_shop_hopping         beige    ya   neutral
1   2  img0002.jpg  coffee_shop_hopping         beige    ya   neutral
2   3  img0003.jpg  coffee_shop_hopping         beige    ya   neutral
3   4  img0004.jpg  coffee_shop_hopping         beige    ya   neutral
4   5  img0005.jpg  coffee_shop_hopping         beige    ya   neutral

In [34]:
print(f"Jumlah outfit : {len(metadata)}")

Jumlah outfit : 6609

In [35]:
print(metadata["aktivitas"].unique())

['coffee_shop_hopping' 'dinner' 'gym_to_caffe' 'hiking' 'smart_casual']

In [36]:
print(metadata["undertone"].unique())

['neutral' 'warm' 'cool']

In [37]:
print(metadata["hijab"].unique())

['ya' 'tidak']

In [38]:
def rule_based_filter(data, aktivitas, undertone, hijab):
    """
    Filter outfit berdasarkan:
    - aktivitas
    - undertone
    - hijab
    """

    filtered = data.copy()

    filtered = filtered[
        filtered["aktivitas"] == aktivitas
    ]

    filtered = filtered[
        filtered["undertone"] == undertone
    ]

    filtered = filtered[
        filtered["hijab"] == hijab
    ]

    return filtered.reset_index(drop=True)

In [39]:
candidate = rule_based_filter(
    metadata,
    aktivitas="dinner",
    undertone="warm",
    hijab="ya"
)

candidate.head()

    id  nama_gambar aktivitas   warna_dominan hijab undertone
0  606  img0606.jpg    dinner  mustard_yellow    ya      warm
1  607  img0607.jpg    dinner  mustard_yellow    ya      warm
2  609  img0609.jpg    dinner  mustard_yellow    ya      warm
3  610  img0610.jpg    dinner  mustard_yellow    ya      warm
4  611  img0611.jpg    dinner  mustard_yellow    ya      warm

In [40]:
print(f"Jumlah candidate outfit : {len(candidate)}")

Jumlah candidate outfit : 126

In [41]:
candidate.sample(10)

       id  nama_gambar aktivitas   warna_dominan hijab undertone
60    840  img0840.jpg    dinner       terracota    ya      warm
97   1408  img1408.jpg    dinner        warm_red    ya      warm
106  1429  img1429.jpg    dinner        warm_red    ya      warm
20    635  img0635.jpg    dinner  mustard_yellow    ya      warm
72   1099  img1099.jpg    dinner           brown    ya      warm
42    818  img0818.jpg    dinner       terracota    ya      warm
84   1123  img1123.jpg    dinner           brown    ya      warm
3     610  img0610.jpg    dinner  mustard_yellow    ya      warm
40    815  img0815.jpg    dinner       terracota    ya      warm
24    640  img0640.jpg    dinner  mustard_yellow    ya      warm

In [44]:
user_input = {
    "aktivitas": "dinner",
    "undertone": "warm",
    "hijab": "ya"
}

In [42]:
def rule_based_filter(data, user_input):

    filtered = data.copy()

    filtered = filtered[
        filtered["aktivitas"] == user_input["aktivitas"]
    ]

    filtered = filtered[
        filtered["undertone"] == user_input["undertone"]
    ]

    filtered = filtered[
        filtered["hijab"] == user_input["hijab"]
    ]

    return filtered.reset_index(drop=True)

In [45]:
candidate = rule_based_filter(metadata, user_input)